language: python
branches:
  only:
    - master
#    - gh-pages
python:
  - "3.4"
addons:
  apt:
    packages:
      - pandoc
install:
  - pip install tox
script:
  - tox
#after_success:
#  - ./tools/publish.sh
