language: python
branches:
  only:
    - master
#    - gh-pages
#python:
#  - "3.4"
install:
  - pip install tox
  - pip install -r requirements.txt
script:
  - tox
#after_success:
#  - ./tools/publish.sh
