sudo: required
dist: trusty
language: python
branches:
  only:
  - master
python:
  - '3.4'
addons:
  apt:
    packages:
    - pandoc
install:
  - pip install tox
script:
  - tox
after_success:
  - ./tools/deploy.sh
